### ISSUE TITLE
What is SDLNNDR and SDLNTDR in input.cgyro

### ISSUE THREAD

**Issue by odstrcilt** [gafusion/gacodeusers#8]
Definition of these two parameters is missing in the cgyro parameter list 
http://gafusion.github.io/doc/cgyro/cgyro_list.html#
and it is not clear from the source code. Is it a second derivative?

**Comment by jcandy** [comment]
Yes, these are the **profile curvature** parameters as discussed in 

https://iopscience.iop.org/article/10.1088/1361-6587/ab759c/pdf

We're not anxious to support the use of these parameters for routine simulations, so that is why they're not documented. However, if there is serious interest in exploring them, we can help with that.
